### PR TITLE
P252PCM support

### PR DESCRIPTION
**Pull request by nostar**
This adds support for P252PCM, part of MMDVM_PCM, a set of utilities to use an analog radio with PiStar as a digital transceiver. The details are here:
http://www.dudetronics.com/index.php/dude-star-radio-project

### CODE REVIEW

**Comment by g4klx** [comment]
Do you plan on doing an NXDN version of this patch?

**Comment by nostar** [comment]
Yes, for completeness sake.  I haven't yet because NXDN is pretty much unheard of around here.

**Comment by nostar** [comment]
I added NXDN2PCM support in P25Gateway, does this all look ok to you?

**Comment by g4klx** [comment]
Hi
I've spent some time thinking about these changes. I think it's wrong to link into the gateways, as they are there for people to use when the MMDVM is being used as a repeater or node. I think it would be a lot better and cleaner if you could talk directly to the host. The protocol is usually much the same as the reflector protocol so wouldn't represent too much work.
Jonathan  G4KLX

    On Thursday, 22 October 2020, 19:11:17 BST, nostar <notifications@github.com> wrote:  
 
 


I added NXDN2PCM support in NXDNGateway, does this all look ok to you?

**Comment by nostar** [comment]
That makes sense for the gateways.  All these patches do is add a XXX2PCM entry into the Reflectors list to make integration into Pistar as easy as possible.  I agree that it wont be much harder to connect XXX2PCM directly to MMDVMHost.  In the case of the MMDVMHost patch though, that allows all Dstar RF received to pass when RadioMode=1.

**Pull request closed without merging**
